name: CI Next js
on:
  push:
    branches:[master]
jobs:
  runs-on: ubuntu-latest

  steps: 
  - name: Setup code
    uses: actions/checkout@v2   
  - name: Setup NodeJS
    uses: actions/setup-node@v2  
    with: 
      node-version: '18'
  - name: Install dependencies
    run: npm i
  - name: Execute tests
    run: npm run test     